from pathlib import Path
from rich.console import Console
from rich.tree import Tree
import typer
console = Console()


def create(
    template: str,
    name: str = typer.Argument("my-project"),
):
    if template != "flask-api":
        console.print(f"[red]Unknown template:[/red] {template}")
        console.print("[yellow]Available templates:[/yellow] flask-api")
        return

    root = Path(name)

    if root.exists():
        console.print(f"[red]Folder already exists:[/red] {name}")
        return

    files = {
        "app.py": '''from flask import Flask

app = Flask(__name__)

@app.route("/")
def home():
    return {"message": "Vibe JS Flask API is alive 😭"}

if __name__ == "__main__":
    app.run(debug=True)
''',
        "requirements.txt": "flask\n",
        ".env.example": "FLASK_ENV=development\n",
        "README.md": f"# {name}\n\nGenerated by Vibe JS 😭\n",
    }

    folders = [
        "routes",
        "services",
        "models",
    ]

    root.mkdir()

    for folder in folders:
        (root / folder).mkdir()

    for path, content in files.items():
        (root / path).write_text(content, encoding="utf-8")

    tree = Tree(f"📁 {name}")

    for folder in folders:
        tree.add(f"📂 {folder}")

    for file in files:
        tree.add(f"📄 {file}")

    console.print("[green]Project created successfully![/green]")
    console.print(tree)